<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Invoicing/InvoiceInfo.proto
 */


namespace Antlena\SDK\Diadoc\Proto\Invoicing;

/**
 * Protobuf enum : Antlena.SDK.Diadoc.Proto.Invoicing.InvoiceFormatVersion
 */
class InvoiceFormatVersion extends \Protobuf\Enum
{

    /**
     * DefaultInvoiceFormatVersion = 0
     */
    const DefaultInvoiceFormatVersion_VALUE = 0;

    /**
     * v5_01 = 1
     */
    const v5_01_VALUE = 1;

    /**
     * v5_02 = 2
     */
    const v5_02_VALUE = 2;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Invoicing\InvoiceFormatVersion
     */
    protected static $DefaultInvoiceFormatVersion = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Invoicing\InvoiceFormatVersion
     */
    protected static $v5_01 = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Invoicing\InvoiceFormatVersion
     */
    protected static $v5_02 = null;

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Invoicing\InvoiceFormatVersion
     */
    public static function DefaultInvoiceFormatVersion()
    {
        if (self::$DefaultInvoiceFormatVersion !== null) {
            return self::$DefaultInvoiceFormatVersion;
        }

        return self::$DefaultInvoiceFormatVersion = new self('DefaultInvoiceFormatVersion', self::DefaultInvoiceFormatVersion_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Invoicing\InvoiceFormatVersion
     */
    public static function v5_01()
    {
        if (self::$v5_01 !== null) {
            return self::$v5_01;
        }

        return self::$v5_01 = new self('v5_01', self::v5_01_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Invoicing\InvoiceFormatVersion
     */
    public static function v5_02()
    {
        if (self::$v5_02 !== null) {
            return self::$v5_02;
        }

        return self::$v5_02 = new self('v5_02', self::v5_02_VALUE);
    }

    /**
     * @param int $value
     * @return \Antlena\SDK\Diadoc\Proto\Invoicing\InvoiceFormatVersion
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::DefaultInvoiceFormatVersion();
            case 1: return self::v5_01();
            case 2: return self::v5_02();
            default: return null;
        }
    }


}

