<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Events/DiadocMessage-PostApi.proto
 */


namespace Antlena\SDK\Diadoc\Proto\Events;

/**
 * Protobuf enum : Antlena.SDK.Diadoc.Proto.Events.CustomDataPatchOperation
 */
class CustomDataPatchOperation extends \Protobuf\Enum
{

    /**
     * Set = 0
     */
    const Set_VALUE = 0;

    /**
     * Remove = 1
     */
    const Remove_VALUE = 1;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Events\CustomDataPatchOperation
     */
    protected static $Set = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Events\CustomDataPatchOperation
     */
    protected static $Remove = null;

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Events\CustomDataPatchOperation
     */
    public static function Set()
    {
        if (self::$Set !== null) {
            return self::$Set;
        }

        return self::$Set = new self('Set', self::Set_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Events\CustomDataPatchOperation
     */
    public static function Remove()
    {
        if (self::$Remove !== null) {
            return self::$Remove;
        }

        return self::$Remove = new self('Remove', self::Remove_VALUE);
    }

    /**
     * @param int $value
     * @return \Antlena\SDK\Diadoc\Proto\Events\CustomDataPatchOperation
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::Set();
            case 1: return self::Remove();
            default: return null;
        }
    }


}

