<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Recognition/Recognition.proto
 */


namespace Antlena\SDK\Diadoc\Proto\Recognition;

/**
 * Protobuf enum : Antlena.SDK.Diadoc.Proto.Recognition.RecognizedDocumentType
 */
class RecognizedDocumentType extends \Protobuf\Enum
{

    /**
     * UnknownRecognizedDocumentType = -1
     */
    const UnknownRecognizedDocumentType_VALUE = -1;

    /**
     * Invoice = 1
     */
    const Invoice_VALUE = 1;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Recognition\RecognizedDocumentType
     */
    protected static $UnknownRecognizedDocumentType = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Recognition\RecognizedDocumentType
     */
    protected static $Invoice = null;

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Recognition\RecognizedDocumentType
     */
    public static function UnknownRecognizedDocumentType()
    {
        if (self::$UnknownRecognizedDocumentType !== null) {
            return self::$UnknownRecognizedDocumentType;
        }

        return self::$UnknownRecognizedDocumentType = new self('UnknownRecognizedDocumentType', self::UnknownRecognizedDocumentType_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Recognition\RecognizedDocumentType
     */
    public static function Invoice()
    {
        if (self::$Invoice !== null) {
            return self::$Invoice;
        }

        return self::$Invoice = new self('Invoice', self::Invoice_VALUE);
    }

    /**
     * @param int $value
     * @return \Antlena\SDK\Diadoc\Proto\Recognition\RecognizedDocumentType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case -1: return self::UnknownRecognizedDocumentType();
            case 1: return self::Invoice();
            default: return null;
        }
    }


}

