<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Invoicing/ExtendedOrganizationInfo.proto
 */


namespace Antlena\SDK\Diadoc\Proto\Invoicing\Organizations;

/**
 * Protobuf enum : Antlena.SDK.Diadoc.Proto.Invoicing.Organizations.OrgType
 */
class OrgType extends \Protobuf\Enum
{

    /**
     * LegalEntity = 1
     */
    const LegalEntity_VALUE = 1;

    /**
     * IndividualEntity = 2
     */
    const IndividualEntity_VALUE = 2;

    /**
     * ForeignEntity = 3
     */
    const ForeignEntity_VALUE = 3;

    /**
     * PhysicalEntity = 4
     */
    const PhysicalEntity_VALUE = 4;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Invoicing\Organizations\OrgType
     */
    protected static $LegalEntity = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Invoicing\Organizations\OrgType
     */
    protected static $IndividualEntity = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Invoicing\Organizations\OrgType
     */
    protected static $ForeignEntity = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Invoicing\Organizations\OrgType
     */
    protected static $PhysicalEntity = null;

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Invoicing\Organizations\OrgType
     */
    public static function LegalEntity()
    {
        if (self::$LegalEntity !== null) {
            return self::$LegalEntity;
        }

        return self::$LegalEntity = new self('LegalEntity', self::LegalEntity_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Invoicing\Organizations\OrgType
     */
    public static function IndividualEntity()
    {
        if (self::$IndividualEntity !== null) {
            return self::$IndividualEntity;
        }

        return self::$IndividualEntity = new self('IndividualEntity', self::IndividualEntity_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Invoicing\Organizations\OrgType
     */
    public static function ForeignEntity()
    {
        if (self::$ForeignEntity !== null) {
            return self::$ForeignEntity;
        }

        return self::$ForeignEntity = new self('ForeignEntity', self::ForeignEntity_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Invoicing\Organizations\OrgType
     */
    public static function PhysicalEntity()
    {
        if (self::$PhysicalEntity !== null) {
            return self::$PhysicalEntity;
        }

        return self::$PhysicalEntity = new self('PhysicalEntity', self::PhysicalEntity_VALUE);
    }

    /**
     * @param int $value
     * @return \Antlena\SDK\Diadoc\Proto\Invoicing\Organizations\OrgType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 1: return self::LegalEntity();
            case 2: return self::IndividualEntity();
            case 3: return self::ForeignEntity();
            case 4: return self::PhysicalEntity();
            default: return null;
        }
    }


}

