<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : DocumentDirection.proto
 */


namespace Antlena\SDK\Diadoc\Proto;

/**
 * Protobuf enum : Antlena.SDK.Diadoc.Proto.DocumentDirection
 */
class DocumentDirection extends \Protobuf\Enum
{

    /**
     * UnknownDocumentDirection = 0
     */
    const UnknownDocumentDirection_VALUE = 0;

    /**
     * Inbound = 1
     */
    const Inbound_VALUE = 1;

    /**
     * Outbound = 2
     */
    const Outbound_VALUE = 2;

    /**
     * Internal = 3
     */
    const Internal_VALUE = 3;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\DocumentDirection
     */
    protected static $UnknownDocumentDirection = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\DocumentDirection
     */
    protected static $Inbound = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\DocumentDirection
     */
    protected static $Outbound = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\DocumentDirection
     */
    protected static $Internal = null;

    /**
     * @return \Antlena\SDK\Diadoc\Proto\DocumentDirection
     */
    public static function UnknownDocumentDirection()
    {
        if (self::$UnknownDocumentDirection !== null) {
            return self::$UnknownDocumentDirection;
        }

        return self::$UnknownDocumentDirection = new self('UnknownDocumentDirection', self::UnknownDocumentDirection_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\DocumentDirection
     */
    public static function Inbound()
    {
        if (self::$Inbound !== null) {
            return self::$Inbound;
        }

        return self::$Inbound = new self('Inbound', self::Inbound_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\DocumentDirection
     */
    public static function Outbound()
    {
        if (self::$Outbound !== null) {
            return self::$Outbound;
        }

        return self::$Outbound = new self('Outbound', self::Outbound_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\DocumentDirection
     */
    public static function Internal()
    {
        if (self::$Internal !== null) {
            return self::$Internal;
        }

        return self::$Internal = new self('Internal', self::Internal_VALUE);
    }

    /**
     * @param int $value
     * @return \Antlena\SDK\Diadoc\Proto\DocumentDirection
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::UnknownDocumentDirection();
            case 1: return self::Inbound();
            case 2: return self::Outbound();
            case 3: return self::Internal();
            default: return null;
        }
    }


}

