<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Organization.proto
 */


namespace Antlena\SDK\Diadoc\Proto;

/**
 * Protobuf enum : Antlena.SDK.Diadoc.Proto.Sociability
 */
class Sociability extends \Protobuf\Enum
{

    /**
     * AllOrganizations = 0
     */
    const AllOrganizations_VALUE = 0;

    /**
     * CounteragentsOnly = 1
     */
    const CounteragentsOnly_VALUE = 1;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Sociability
     */
    protected static $AllOrganizations = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Sociability
     */
    protected static $CounteragentsOnly = null;

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Sociability
     */
    public static function AllOrganizations()
    {
        if (self::$AllOrganizations !== null) {
            return self::$AllOrganizations;
        }

        return self::$AllOrganizations = new self('AllOrganizations', self::AllOrganizations_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Sociability
     */
    public static function CounteragentsOnly()
    {
        if (self::$CounteragentsOnly !== null) {
            return self::$CounteragentsOnly;
        }

        return self::$CounteragentsOnly = new self('CounteragentsOnly', self::CounteragentsOnly_VALUE);
    }

    /**
     * @param int $value
     * @return \Antlena\SDK\Diadoc\Proto\Sociability
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::AllOrganizations();
            case 1: return self::CounteragentsOnly();
            default: return null;
        }
    }


}

