<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Documents/Document.proto
 */


namespace Antlena\SDK\Diadoc\Proto\Documents;

/**
 * Protobuf enum : Antlena.SDK.Diadoc.Proto.Documents.MessageType
 */
class MessageType extends \Protobuf\Enum
{

    /**
     * Unknown = 0
     */
    const Unknown_VALUE = 0;

    /**
     * Message = 1
     */
    const Message_VALUE = 1;

    /**
     * Draft = 2
     */
    const Draft_VALUE = 2;

    /**
     * Template = 3
     */
    const Template_VALUE = 3;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Documents\MessageType
     */
    protected static $Unknown = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Documents\MessageType
     */
    protected static $Message = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Documents\MessageType
     */
    protected static $Draft = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Documents\MessageType
     */
    protected static $Template = null;

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Documents\MessageType
     */
    public static function Unknown()
    {
        if (self::$Unknown !== null) {
            return self::$Unknown;
        }

        return self::$Unknown = new self('Unknown', self::Unknown_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Documents\MessageType
     */
    public static function Message()
    {
        if (self::$Message !== null) {
            return self::$Message;
        }

        return self::$Message = new self('Message', self::Message_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Documents\MessageType
     */
    public static function Draft()
    {
        if (self::$Draft !== null) {
            return self::$Draft;
        }

        return self::$Draft = new self('Draft', self::Draft_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Documents\MessageType
     */
    public static function Template()
    {
        if (self::$Template !== null) {
            return self::$Template;
        }

        return self::$Template = new self('Template', self::Template_VALUE);
    }

    /**
     * @param int $value
     * @return \Antlena\SDK\Diadoc\Proto\Documents\MessageType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::Unknown();
            case 1: return self::Message();
            case 2: return self::Draft();
            case 3: return self::Template();
            default: return null;
        }
    }


}

