<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Documents/ReceiptStatus.proto
 */


namespace Antlena\SDK\Diadoc\Proto\Documents;

/**
 * Protobuf enum : Antlena.SDK.Diadoc.Proto.Documents.ReceiptStatus
 */
class ReceiptStatus extends \Protobuf\Enum
{

    /**
     * UnknownReceiptStatus = 0
     */
    const UnknownReceiptStatus_VALUE = 0;

    /**
     * ReceiptStatusNone = 1
     */
    const ReceiptStatusNone_VALUE = 1;

    /**
     * ReceiptStatusFinished = 2
     */
    const ReceiptStatusFinished_VALUE = 2;

    /**
     * ReceiptStatusHaveToCreateReceipt = 3
     */
    const ReceiptStatusHaveToCreateReceipt_VALUE = 3;

    /**
     * ReceiptStatusWaitingForReceipt = 4
     */
    const ReceiptStatusWaitingForReceipt_VALUE = 4;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Documents\ReceiptStatus
     */
    protected static $UnknownReceiptStatus = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Documents\ReceiptStatus
     */
    protected static $ReceiptStatusNone = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Documents\ReceiptStatus
     */
    protected static $ReceiptStatusFinished = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Documents\ReceiptStatus
     */
    protected static $ReceiptStatusHaveToCreateReceipt = null;

    /**
     * @var \Antlena\SDK\Diadoc\Proto\Documents\ReceiptStatus
     */
    protected static $ReceiptStatusWaitingForReceipt = null;

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Documents\ReceiptStatus
     */
    public static function UnknownReceiptStatus()
    {
        if (self::$UnknownReceiptStatus !== null) {
            return self::$UnknownReceiptStatus;
        }

        return self::$UnknownReceiptStatus = new self('UnknownReceiptStatus', self::UnknownReceiptStatus_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Documents\ReceiptStatus
     */
    public static function ReceiptStatusNone()
    {
        if (self::$ReceiptStatusNone !== null) {
            return self::$ReceiptStatusNone;
        }

        return self::$ReceiptStatusNone = new self('ReceiptStatusNone', self::ReceiptStatusNone_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Documents\ReceiptStatus
     */
    public static function ReceiptStatusFinished()
    {
        if (self::$ReceiptStatusFinished !== null) {
            return self::$ReceiptStatusFinished;
        }

        return self::$ReceiptStatusFinished = new self('ReceiptStatusFinished', self::ReceiptStatusFinished_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Documents\ReceiptStatus
     */
    public static function ReceiptStatusHaveToCreateReceipt()
    {
        if (self::$ReceiptStatusHaveToCreateReceipt !== null) {
            return self::$ReceiptStatusHaveToCreateReceipt;
        }

        return self::$ReceiptStatusHaveToCreateReceipt = new self('ReceiptStatusHaveToCreateReceipt', self::ReceiptStatusHaveToCreateReceipt_VALUE);
    }

    /**
     * @return \Antlena\SDK\Diadoc\Proto\Documents\ReceiptStatus
     */
    public static function ReceiptStatusWaitingForReceipt()
    {
        if (self::$ReceiptStatusWaitingForReceipt !== null) {
            return self::$ReceiptStatusWaitingForReceipt;
        }

        return self::$ReceiptStatusWaitingForReceipt = new self('ReceiptStatusWaitingForReceipt', self::ReceiptStatusWaitingForReceipt_VALUE);
    }

    /**
     * @param int $value
     * @return \Antlena\SDK\Diadoc\Proto\Documents\ReceiptStatus
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::UnknownReceiptStatus();
            case 1: return self::ReceiptStatusNone();
            case 2: return self::ReceiptStatusFinished();
            case 3: return self::ReceiptStatusHaveToCreateReceipt();
            case 4: return self::ReceiptStatusWaitingForReceipt();
            default: return null;
        }
    }


}

